// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVf4vbZdGReKxhJpkuQzOhGrtRWGAAIa0',
    appId: '1:786330643683:web:5798d28b0a09a5e6a1e9d6',
    messagingSenderId: '786330643683',
    projectId: 'next-up-consultoria',
    authDomain: 'next-up-consultoria.firebaseapp.com',
    storageBucket: 'next-up-consultoria.firebasestorage.app',
    measurementId: 'G-WZTTLCLJCD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADP9VZT0CvkrZgQIirVdllAnKblRRC0b0',
    appId: '1:786330643683:android:8c405d3ca2c25572a1e9d6',
    messagingSenderId: '786330643683',
    projectId: 'next-up-consultoria',
    storageBucket: 'next-up-consultoria.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-BpAoW_uh9ZemmlVb6LNcT8NqjrPsiQU',
    appId: '1:786330643683:ios:7e3505f16634086ea1e9d6',
    messagingSenderId: '786330643683',
    projectId: 'next-up-consultoria',
    storageBucket: 'next-up-consultoria.firebasestorage.app',
    iosBundleId: 'app.ios.nextupconsultoria',
  );
}
