// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0ceXlaMU84-7y6LMrCZaTon1KikHHUxM',
    appId: '1:530604765160:web:6f2982e080d089317ebe5d',
    messagingSenderId: '530604765160',
    projectId: 'mda-workforce-239e4',
    authDomain: 'mda-workforce-239e4.firebaseapp.com',
    storageBucket: 'mda-workforce-239e4.firebasestorage.app',
    measurementId: 'G-0DSVT5FQ49',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-kcJcmSbhPFqp0sf-JcGlWWf2gtTRhGs',
    appId: '1:530604765160:android:1aa0f539bced49b27ebe5d',
    messagingSenderId: '530604765160',
    projectId: 'mda-workforce-239e4',
    storageBucket: 'mda-workforce-239e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx4YPUNponH0hSY20wCLXFKir1CaUBFN8',
    appId: '1:530604765160:ios:c911d4f611f860137ebe5d',
    messagingSenderId: '530604765160',
    projectId: 'mda-workforce-239e4',
    storageBucket: 'mda-workforce-239e4.firebasestorage.app',
    iosBundleId: 'com.partnerbfacmobile.MDA',
  );
}
