// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKSHAL9jaANgvfD14kwCzUG57ByyWJwfI',
    appId: '1:869348706938:web:64c12d0cc8b0c292c789c3',
    messagingSenderId: '869348706938',
    projectId: 'oklahoma-pharmacist',
    authDomain: 'oklahoma-pharmacist.firebaseapp.com',
    storageBucket: 'oklahoma-pharmacist.firebasestorage.app',
    measurementId: 'G-7ZEHVC50E6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPecOxtwsdTVXBI-n-Swpnno5MwUDkH5o',
    appId: '1:869348706938:android:ba9049c4753950dac789c3',
    messagingSenderId: '869348706938',
    projectId: 'oklahoma-pharmacist',
    storageBucket: 'oklahoma-pharmacist.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNuSPH-0xYfPntoE8s8-cOmJJh1mQAzWw',
    appId: '1:869348706938:ios:05c959765464e637c789c3',
    messagingSenderId: '869348706938',
    projectId: 'oklahoma-pharmacist',
    storageBucket: 'oklahoma-pharmacist.firebasestorage.app',
    iosBundleId: 'ios.bfac.opha',
  );
}
