// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoUfESd00kN3iaENFTGSFsV1B3EAnAfrE',
    appId: '1:720894411577:web:a7615c102dcf9112ab1ee8',
    messagingSenderId: '720894411577',
    projectId: 'mississippi-blood-servic-cffcb',
    authDomain: 'mississippi-blood-servic-cffcb.firebaseapp.com',
    storageBucket: 'mississippi-blood-servic-cffcb.firebasestorage.app',
    measurementId: 'G-CL8KC2T51B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAgKmkrh25g3DPQTxlhmXIpKJt1LmUBnQ',
    appId: '1:720894411577:android:4b8d92080e2c4ed3ab1ee8',
    messagingSenderId: '720894411577',
    projectId: 'mississippi-blood-servic-cffcb',
    storageBucket: 'mississippi-blood-servic-cffcb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCevDYbBeOfXhbtNKC7m30olYUiig1y70M',
    appId: '1:720894411577:ios:69f0fc3742e24830ab1ee8',
    messagingSenderId: '720894411577',
    projectId: 'mississippi-blood-servic-cffcb',
    storageBucket: 'mississippi-blood-servic-cffcb.firebasestorage.app',
    iosBundleId: 'app.ios.mbs',
  );
}
