// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnD_VNw_akJ6Vd7eLYjcV9rl9CH_UcD5s',
    appId: '1:904657405963:web:c600efccd90974fffcdf0e',
    messagingSenderId: '904657405963',
    projectId: 'associated-industries',
    authDomain: 'associated-industries.firebaseapp.com',
    storageBucket: 'associated-industries.firebasestorage.app',
    measurementId: 'G-BP6J2G3MP6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuIvYdvjFXYuNur1b7sAzlEFjeW7diEm4',
    appId: '1:904657405963:android:c6a054e5a23f879afcdf0e',
    messagingSenderId: '904657405963',
    projectId: 'associated-industries',
    storageBucket: 'associated-industries.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFATqj3BgX8lw41vHJsvVGHFq3yNyJwMQ',
    appId: '1:904657405963:ios:920f208e1265a6e0fcdf0e',
    messagingSenderId: '904657405963',
    projectId: 'associated-industries',
    storageBucket: 'associated-industries.firebasestorage.app',
    iosBundleId: 'app.ios.associatedindustries',
  );
}
