// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHrDVxgPzNnOvZTHbPg9iuEDGFAj-osV0',
    appId: '1:1062869428187:web:042b2efbabf6985f5e29fe',
    messagingSenderId: '1062869428187',
    projectId: 'central-holmes',
    authDomain: 'central-holmes.firebaseapp.com',
    storageBucket: 'central-holmes.firebasestorage.app',
    measurementId: 'G-401283ZZFD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhWyx0A7dZPlzq-uKmHcz4tbI376qYJKk',
    appId: '1:1062869428187:android:c5b4c19177dd08715e29fe',
    messagingSenderId: '1062869428187',
    projectId: 'central-holmes',
    storageBucket: 'central-holmes.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJxwfgHbyEUKzACF8wItb4jZumHIzcXw8',
    appId: '1:1062869428187:ios:1d959b03b95ac6aa5e29fe',
    messagingSenderId: '1062869428187',
    projectId: 'central-holmes',
    storageBucket: 'central-holmes.firebasestorage.app',
    iosBundleId: 'app.ios.centralholmes',
  );
}
