// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7xGlkPZRY22atpeWIrnzbzWVeUzLDmj4',
    appId: '1:963849600697:web:3fc84d746a4611d2b12568',
    messagingSenderId: '963849600697',
    projectId: 'oak-ridge-baptist-church-b7162',
    authDomain: 'oak-ridge-baptist-church-b7162.firebaseapp.com',
    storageBucket: 'oak-ridge-baptist-church-b7162.firebasestorage.app',
    measurementId: 'G-FC46723873',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_Z3j1IhTBJE1-M30Jg8R2VgyslV_CZHw',
    appId: '1:963849600697:android:b0f227b3f2b79b3cb12568',
    messagingSenderId: '963849600697',
    projectId: 'oak-ridge-baptist-church-b7162',
    storageBucket: 'oak-ridge-baptist-church-b7162.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZsPU2sKk9rIGfgVmv5jYCHL6XX_bOHY4',
    appId: '1:963849600697:ios:4729ac5770ab4025b12568',
    messagingSenderId: '963849600697',
    projectId: 'oak-ridge-baptist-church-b7162',
    storageBucket: 'oak-ridge-baptist-church-b7162.firebasestorage.app',
    iosBundleId: 'com.partnerbuyfromachristian.oakridgechurch',
  );
}
