// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5Ppdrs-A0OiyVmbWKCNee-pGOcTevh3o',
    appId: '1:650091558904:web:2887c5e8fa9181ca63480d',
    messagingSenderId: '650091558904',
    projectId: 'flowood-police',
    authDomain: 'flowood-police.firebaseapp.com',
    storageBucket: 'flowood-police.firebasestorage.app',
    measurementId: 'G-FJF9FJML0C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpvKsRuK-bmktnQYKD0c11H8IXXB1jBQg',
    appId: '1:650091558904:android:20e8f5a1d1bba88063480d',
    messagingSenderId: '650091558904',
    projectId: 'flowood-police',
    storageBucket: 'flowood-police.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvsJzDlq94qrXNRIaK--OuYRWZ5kL3Zxk',
    appId: '1:650091558904:ios:238e5a94012daad963480d',
    messagingSenderId: '650091558904',
    projectId: 'flowood-police',
    storageBucket: 'flowood-police.firebasestorage.app',
    iosBundleId: 'app.ios.flowoodpolice',
  );
}
