// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        return ios; // fallback to iOS if platform detection fails
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx8yEjBRy5n-3d4y_akpV3Xwo0Mmslg5g',
    appId: '1:521464985669:android:f5df7e5bc1ae87197e4b2c',
    messagingSenderId: '521464985669',
    projectId: 'harold-lefty-williams',
    storageBucket: 'harold-lefty-williams.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQ7jRbeaspojrbUwbdBsk2bVYQd2ng3zE',
    appId: '1:521464985669:ios:5fe583468c0609b37e4b2c',
    messagingSenderId: '521464985669',
    projectId: 'harold-lefty-williams',
    storageBucket: 'harold-lefty-williams.firebasestorage.app',
    iosBundleId: 'app.ios.haroldleftywilliams',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDUihOvaSJLM1YC3xLWfpIfQrbdlZnsso',
    appId: '1:521464985669:web:3d665da2461a70b57e4b2c',
    messagingSenderId: '521464985669',
    projectId: 'harold-lefty-williams',
    authDomain: 'harold-lefty-williams.firebaseapp.com',
    storageBucket: 'harold-lefty-williams.firebasestorage.app',
    measurementId: 'G-6W7E9Y5WL7',
  );

}