// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFEZRUkHEPdZjsflzeTA_2Bo4XkFQf00E',
    appId: '1:181346515703:web:73a9660746b0fdbe6cb1f2',
    messagingSenderId: '181346515703',
    projectId: 'diffee-ford-lincoln',
    authDomain: 'diffee-ford-lincoln.firebaseapp.com',
    storageBucket: 'diffee-ford-lincoln.firebasestorage.app',
    measurementId: 'G-SYRLM53JJ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZAn2kE3lO2jSkTqJajnx6JczXK88YBdQ',
    appId: '1:181346515703:android:f7cb5613dc5606f86cb1f2',
    messagingSenderId: '181346515703',
    projectId: 'diffee-ford-lincoln',
    storageBucket: 'diffee-ford-lincoln.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaoraelXhTM6wbNi5HfyRc77-ClJqsUM0',
    appId: '1:181346515703:ios:a335327608c6ab346cb1f2',
    messagingSenderId: '181346515703',
    projectId: 'diffee-ford-lincoln',
    storageBucket: 'diffee-ford-lincoln.firebasestorage.app',
    iosBundleId: 'app.ios.diffeefordlincoln',
  );
}
