// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqFpQjj0_tOffgJRFa3XLINh-yy57VZts',
    appId: '1:362068981425:web:0c1f2115cf70cce23c9490',
    messagingSenderId: '362068981425',
    projectId: 'nil-management',
    authDomain: 'nil-management.firebaseapp.com',
    storageBucket: 'nil-management.firebasestorage.app',
    measurementId: 'G-E4BE9LWH9T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuk9wzqRdaGLxXOLbIbcPCZ9Ng_q6Lze0',
    appId: '1:362068981425:android:464a504bc0d2fa3e3c9490',
    messagingSenderId: '362068981425',
    projectId: 'nil-management',
    storageBucket: 'nil-management.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8cwInPGyPbs560F5KIWyveKNkrPegESg',
    appId: '1:362068981425:ios:64f1f3d06ce077403c9490',
    messagingSenderId: '362068981425',
    projectId: 'nil-management',
    storageBucket: 'nil-management.firebasestorage.app',
    iosBundleId: 'app.ios.nilmanagement',
  );
}
