// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_gvHw_1UooCHnYbRZKjlk5OBeaW9lFVQ',
    appId: '1:575220937158:web:6776b2af0775e0c2af02c7',
    messagingSenderId: '575220937158',
    projectId: 'kiki-williams-f6028',
    authDomain: 'kiki-williams-f6028.firebaseapp.com',
    storageBucket: 'kiki-williams-f6028.firebasestorage.app',
    measurementId: 'G-XP9E8H4JW8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgNbYjI-JV0W2XYpvEa660TDinE0trbOs',
    appId: '1:575220937158:android:7b9fac4d8089b3feaf02c7',
    messagingSenderId: '575220937158',
    projectId: 'kiki-williams-f6028',
    storageBucket: 'kiki-williams-f6028.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtAqEggh6s7hDVPKTlHVIQscnleuN7S8U',
    appId: '1:575220937158:ios:af1d666e3033de45af02c7',
    messagingSenderId: '575220937158',
    projectId: 'kiki-williams-f6028',
    storageBucket: 'kiki-williams-f6028.firebasestorage.app',
    iosBundleId: 'app.ios.kikiwilliams',
  );
}
