// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACeMCNVbqcZhb8HKbGu9o_7Sv1lGnxizE',
    appId: '1:204642367313:web:6e4231af6f86fecffe8570',
    messagingSenderId: '204642367313',
    projectId: 'brandon-first-responders',
    authDomain: 'brandon-first-responders.firebaseapp.com',
    storageBucket: 'brandon-first-responders.firebasestorage.app',
    measurementId: 'G-7HPF50WKVY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9Xb3wMD-Uhmu8um_mho82y8H82DBC4Ew',
    appId: '1:204642367313:android:80f07905748de1a2fe8570',
    messagingSenderId: '204642367313',
    projectId: 'brandon-first-responders',
    storageBucket: 'brandon-first-responders.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsjYVQ6GLatD7MGDFtdVVAmPi-ixbFcjw',
    appId: '1:204642367313:ios:dc741df5ceee8344fe8570',
    messagingSenderId: '204642367313',
    projectId: 'brandon-first-responders',
    storageBucket: 'brandon-first-responders.firebasestorage.app',
    iosBundleId: 'app.ios.brandonfirstresponders',
  );
}
