// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADkTEGZahN2UV1LyWHh96mT31FRMlUrTc',
    appId: '1:308668237939:web:fcd60abae7952bf09dc206',
    messagingSenderId: '308668237939',
    projectId: 'mahmoud-sebie-961c7',
    authDomain: 'mahmoud-sebie-961c7.firebaseapp.com',
    storageBucket: 'mahmoud-sebie-961c7.firebasestorage.app',
    measurementId: 'G-P1V87K8JRW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM8jNEQSC_4DgMH83Tuj6ydvfz9wT1Azw',
    appId: '1:308668237939:android:c7eeb73f12673f119dc206',
    messagingSenderId: '308668237939',
    projectId: 'mahmoud-sebie-961c7',
    storageBucket: 'mahmoud-sebie-961c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN6xmHdokh6UQzM_7aeCEnzPZwzXJz3uc',
    appId: '1:308668237939:ios:9be748bcace2e3cf9dc206',
    messagingSenderId: '308668237939',
    projectId: 'mahmoud-sebie-961c7',
    storageBucket: 'mahmoud-sebie-961c7.firebasestorage.app',
    iosBundleId: 'app.ios.mahmoudsebie',
  );
}
