// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgy-NNZxU_X4uyD3Bz5nCJzBG-p_l9ibM',
    appId: '1:1039857978257:web:0cb1c4f147920fdba8a830',
    messagingSenderId: '1039857978257',
    projectId: 'da-crazy-hawaiian-8a400',
    authDomain: 'da-crazy-hawaiian-8a400.firebaseapp.com',
    storageBucket: 'da-crazy-hawaiian-8a400.firebasestorage.app',
    measurementId: 'G-JDRVV1V3RB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY7S4xinx3r37y1WQAa3ksmTzxVAiltAk',
    appId: '1:1039857978257:android:025b3a870b7af7caa8a830',
    messagingSenderId: '1039857978257',
    projectId: 'da-crazy-hawaiian-8a400',
    storageBucket: 'da-crazy-hawaiian-8a400.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZHbdeaNwGV-rn_fPBGAIB5evbO7jZ5cc',
    appId: '1:1039857978257:ios:542d7daf5be777f7a8a830',
    messagingSenderId: '1039857978257',
    projectId: 'da-crazy-hawaiian-8a400',
    storageBucket: 'da-crazy-hawaiian-8a400.firebasestorage.app',
    iosBundleId: 'app.ios.dacrazyhawaiian',
  );
}
