// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnCFWeAmC_rx3wCW-kgG7bi9tYHkJ4GNA',
    appId: '1:120940615600:web:0a143fc471800a06656875',
    messagingSenderId: '120940615600',
    projectId: 'live-at-the-garden-9eb57',
    authDomain: 'live-at-the-garden-9eb57.firebaseapp.com',
    storageBucket: 'live-at-the-garden-9eb57.firebasestorage.app',
    measurementId: 'G-MSCQYSH03B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdzd-7W6vzx_jL0k5OfL8N-6gHITRmA5s',
    appId: '1:120940615600:android:59e8019459392ffe656875',
    messagingSenderId: '120940615600',
    projectId: 'live-at-the-garden-9eb57',
    storageBucket: 'live-at-the-garden-9eb57.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCafCNKS3C6HEaDVOuwSL0ENf5jXg71Kmg',
    appId: '1:120940615600:ios:a663184e947ced56656875',
    messagingSenderId: '120940615600',
    projectId: 'live-at-the-garden-9eb57',
    storageBucket: 'live-at-the-garden-9eb57.firebasestorage.app',
    iosBundleId: 'com.partnerbfacmobile.BotanicGarden',
  );
}
