// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUfyRg72iW8R6F0iwXtGVm7hvXFYw1yCo',
    appId: '1:202242835455:web:c1417e0f8498bf022b5dca',
    messagingSenderId: '202242835455',
    projectId: 'bob-stoops-546de',
    authDomain: 'bob-stoops-546de.firebaseapp.com',
    storageBucket: 'bob-stoops-546de.firebasestorage.app',
    measurementId: 'G-662LFVN7H0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCAZToP5ZCv-aqmn1tyNqnazcBNX_YYBs',
    appId: '1:202242835455:android:dbe5e07454ff6f822b5dca',
    messagingSenderId: '202242835455',
    projectId: 'bob-stoops-546de',
    storageBucket: 'bob-stoops-546de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHwure3PZVSlIuCv4wpKzJTQ2TMlh9NMo',
    appId: '1:202242835455:ios:5a0a3bc23cda17e72b5dca',
    messagingSenderId: '202242835455',
    projectId: 'bob-stoops-546de',
    storageBucket: 'bob-stoops-546de.firebasestorage.app',
    iosBundleId: 'com.j0d3d2fffc57.www',
  );
}
